### ISSUE TITLE
Driver statistics endpoint

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-rest-api#33]
### Objective
The statistics endpoint should contains computed pieces of information concerning the specified driver. For now the most urgent piece of information that should be provided is the total number of kilometers driven. Some interesting data would be: the total number of rides or the total number of visited locations.

This would be used by the [Journal de Bord web application](https://github.com/Lofaloa/journal-de-bord-spa) to show a simple overview of the driver progress. The driver has an objective of kilometers to drive. Knowing the total driven distance, we can compute its progress.

### Implementation
The data should be exposed at `<host>/api/drivers/<driverId>/statistics`. And the response body should contain a JSON schema close to the this:
```json
{
    "totalDistance": 576,
    "rides": 12,
    "locations": 5
}
```
The error handling should be similar to the `GET` driver endpoint.

### Tasks
- [x] Create the `<host>/api/drivers/<driverId>/statistics` endpoint in the `DriverController` class.
- [x] Create a `countDriverRides` method in the `RideRepository` class.
- [x] Create a `sumDriverRidesDistance` method in the `RideRepository` class.
- [x] Create a `countDriverLocations` method in the `LocationRepository` class.
- [x] Create a new `DriverStatistics` class that can be used as a response, its field are the one described here above.
- [x] Create a `getDriverStatisticsFor(String identifier)` method in the `DriverService`.
- [x] Implement the endpoint method in the `DriverController` with the created symbols.

### Resources
- [Does Spring Data JPA have any way to count entities using method name resolving?](https://stackoverflow.com/questions/10696490/does-spring-data-jpa-have-any-way-to-count-entites-using-method-name-resolving)
- [Does Spring Data JPA have any way to sum an entity column using method name resolving?](https://stackoverflow.com/questions/55495369/does-spring-data-jpa-have-any-way-to-sum-an-entity-column-using-method-name-reso)
