### ISSUE TITLE
Implement security

### ISSUE THREAD

**Issue by Lofaloa** [Lofaloa/journal-de-bord-rest-api#5]
### Overview
The application is a resource server. It should be secured so that each user can only access its journal. The following tutorial can be used to implement that: [OAuth 2.0 Resource Server With Spring Security 5](baeldung.com/spring-security-oauth-resource-server).

### Tasks
- [x] Add a dependency to [spring-boot-starter-oauth2-resource-server](https://search.maven.org/search?q=spring-boot-starter-oauth2-resource-server) package (2.4.2).
- [x]  Create the security configuration class: we want to use JWT tokens.
- [x] Document the required application properties.
- [x] Create a drive controller
- [x] test user id against the resources to determine if a user can access it
